### ISSUE TITLE
Homebrew cask

### ISSUE THREAD

**Issue by danyim** [graphcool/graphql-playground#147]
Could one of the contributors register the desktop version as a homebrew cask for Mac users?

Details here: https://github.com/caskroom/homebrewcask/blob/master/doc/development/adding_a_cask.md

Ideally after setting this up, Mac users can run `brew cask install graphql-playground`, which will subscribe to new releases via `brew update`.

**Comment by DevanB** [comment]
Someone has already submitted an issue to add this to home-brew over at #142. But I think adding it as a cask is better.

In addition, I haven't found where the app is using the built-in Electron updater. It's pretty easy to add. If this is something that sounds helpful, I'll be glad to submit a PR! It'd help everyone because they wouldn't need to check GitHub for updates!

**Comment by timsuchanek** [comment]
That sounds very interesting! @DevanB that would be really cool, I would love to see a PR for that!
Have you also looked into https://github.com/zeit/hazel? And did you already use the built-in Electron updater? You can also join our slack and ping me there, I'm @tim2 there so we can discuss this!

**Comment by DevanB** [comment]
@timsuchanek For sure, I'm on the Slack team; I'll ping you there!

**Comment by cjoudrey** [comment]
Added to `cask` here: https://github.com/caskroom/homebrew-cask/pull/41771

**Comment by zimme** [comment]
I guess this can be closed?

**Comment by timsuchanek** [comment]
Thanks, I just update the README with the instructions!
