### ISSUE TITLE
Version string in Electron app setting is wrong

### ISSUE THREAD

**Issue by marktani** [graphcool/graphql-playground#662]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What is the expected behavior?

It prints the right version string.

#### What is the actual behavior?

![image](https://user-images.githubusercontent.com/1780597/39698671-fcc1bb04-51f5-11e8-8db2-f3c18fcce6fe.png)

**Comment by Huvik** [comment]
This is not a bug, because electron version is different from react one. Elecron app wraps react app what is version bottom. And why is that? If we have one version of package version would increase so fast because when you want to fix something in electron playground you would need to release all packages and vice versa :)
